version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: feedfm-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - radnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: feedfm-phpmyadmin
    restart: unless-stopped
    ports:
    - 8080:80
    volumes:
      - ./docker-compose/phpmyadmin:/sessions
    networks:
      - radnet

networks:
  radnet:
    driver: bridge
